import bcrypt from 'bcryptjs';
  const data = {
    users: [
        {
          name: 'Basir',
          email: 'admin@example.com',
          password: bcrypt.hashSync('1234', 8),
          isAdmin: true,
        },
        {
          name: 'John',
          email: 'user@example.com',
          password: bcrypt.hashSync('1234', 8),
          isAdmin: false,
        },
      ],
    products:[
        {
            _id:1,
            name:"Nike slim Shirt",
            category:"Shirt" ,
            image:'/images/p1.jfif',
            price:120,
            countInStock:150,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:2,
            name:"Adidas fit Shirt",
            category:"Shirt" ,
            image:'/images/p2.jfif',
            price:100,
            countInStock:15,
            brand:'Adidas',
            rating:5,
            numReviews:15,
            description:'bad quality product',
        },
        {
            _id:3,
            name:"Nike slim Shirt",
            category:"Shirt" ,
            image:'/images/p1.jfif',
            price:120,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:4,
            name:"Nike slim Shirt",
            category:"Shirt" ,
            image:'/images/p1.jfif',
            price:120,
            countInStock:250,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:5,
            name:"puma slim pant",
            category:"pant" ,
            image:'/images/p5.jfif',
            price:120,
            countInStock:0,
            brand:'puma',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        }
    ]
}
export default data ;